### ISSUE TITLE
Trim Issue, Roll Display

### ISSUE THREAD

**Issue by somasatori** [thenomain/GMCCG#1]
For the display.roll-outlet.single attribute, you have a misplaced 't' in the line above the trim function.

Currently it looks like this:
&display.roll-output.single nWoD Roller <nr>=
	cat( 
		%b, 
		Result:, t
		trim( 
			wrap( %q1 -- [u( display.interpret-roll-output, %qr )], 
				sub( width( %# ), 10 ), l, , , 10 
			), 
			r, %b 
		)
	)

It should look like this:
&display.roll-output.single nWoD Roller <nr>=
	cat( 
		%b, Result:, 
		trim( 
			wrap( %q1 -- [u( display.interpret-roll-output, %qr )], 
				sub( width( %# ), 10 ), l, , , 10 
			), 
			r, %b 
		)
	)

The difference is this:
With:
={ Shen rolls 5 Dice }==============================================================================
  Roll: 5
  Result: ttrim( wrap( Success (2) -- (1 10 7 1 10 4 5), sub( width( #13 ), 10 ), l, , , 10 ), r,   )
========================================================={ success (public) }=

Without:
={ Shen rolls 5 Dice }==============================================================================
  Roll: 5
  Result: Success (1) -- (7 4 2 8 2)
========================================================={ success (public) }=

**Comment by thenomain** [comment]
Typo fixed. Thanks.
