### ISSUE TITLE
Function name spelled wrong

### ISSUE THREAD

**Issue by ADHdev** [thenomain/GMCCG#11]
&f.prerequisite.other was spelled &f.prerequsite.other, which caused problems when XP spends went through: prereq checks weren't run. I fixed it by leaving the old version in and copying it to the correct attribute so that any references to the misspelled version would still work, but references to the correct version would also work.

**Comment by ADHdev** [comment]
I did the same for the other &f.prereq functions. They were also misspelled, and referenced elsewhere (during xp/spend), so I'm not sure they were getting correctly called.

**Comment by thenomain** [comment]
In file 8d (Chargen, Prerequisites Check), all instances of "&f.prerequisite" -> "&f.prerequisite". 3 instances changed. Did I miss anything?

**Comment by thenomain** [comment]
This was left open too long by yours truly. Closing it for now. Re-open if there are more issues please. Thanks.

commit 1fac59e23e44eeb7f4441f6332f892463c42d65a
