### ISSUE TITLE
Max trait sub-stats not being read

### ISSUE THREAD

**Issue by ADHdev** [thenomain/GMCCG#12]
In GMCCG/1 - Data Dictionary/1a - Setup.txt, line 702, the code:

`lattr( %!/.max.trait.[u( .value_full, %0, bio.template )].* ), 
`
should be:

`lattr( %!/.max_trait.[u( .value_full, %0, bio.template )].* ), 
`

**Comment by thenomain** [comment]
I do not see any difference between the before and after. The code is currently at: https://github.com/thenomain/GMCCG/blob/master/1%20-%20Data%20Dictionary/1a%20-%20Setup.txt#L718

`lattr( %!/.max.trait.[u( .value_full, %0, bio.template )].* ),`
