### ISSUE TITLE
Missing reference attribute

### ISSUE THREAD

**Issue by skewskewskew** [thenomain/GMCCG#17]
https://github.com/thenomain/GMCCG/blob/0384747909b3e598e8627bbe85e862e391487ddd/7%20-%20Sheet/7e%20-%20Sheet%20Rows.txt#L3

Calling d.sheet before it's set. Should include:

@fo me=&d.sheet me=[search( name=Sheet: Rows )]

**Comment by thenomain** [comment]
Fixed; see commit comments for more.
