### ISSUE TITLE
Missing f.allocated.power-trait.mage

### ISSUE THREAD

**Issue by skewskewskew** [thenomain/GMCCG#18]
https://github.com/thenomain/GMCCG/blob/0384747909b3e598e8627bbe85e862e391487ddd/Z%20-%20Game%20Lines/Mage%20the%20Awakening/MtA1%20-%20Core.txt#L3103

There is no f.allocated.power-trait.mage ... this is probably because Fallen World didn't allow using Merit Dots on Gnosis.

Try this?

&f.allocated.power-trait.mage [v(d.cg)]=
	mul( 
		dec( first( get( %0/_advantage.gnosis ), . )), 
		5 
	)

**Comment by thenomain** [comment]
Whups. Fixed.
