### ISSUE TITLE
Question: Setting up XP SQL Database

### ISSUE THREAD

**Issue by lmclarke** [thenomain/GMCCG#20]
For newcomers to MUX and your average everyday idiots (me), I was wondering if there might be a walk-through for setting up the SQL table(s?) needed to use the package. I got through the XP section and realized there's a whole block that's setting up a table, but I don't have a table. I don't think I have sql functions at all. Using MUX 2.10.1.14.

**Comment by thenomain** [comment]
This was closed, but it's worth noting that the SQL blocks (`CREATE TABLE`, etc.) are to be run from the MySQL command line. It could be more spelled out, but the whole XP system is halfway thrown-together as it is.
