### ISSUE TITLE
Double Function - Supposed to be workhorse?

### ISSUE THREAD

**Issue by lmclarke** [thenomain/GMCCG#21]
https://github.com/thenomain/GMCCG/blob/2ea85663666d10288ebeb5b1404f3096faf94556/2%20-%20Support%20Functions/2d%20-%20User-Defined%20Functions.txt#L1205

The above function has the same attribute, which causes this to override it. I believe it's supposed to be f.shiftstat.workhorse?

**Comment by lmclarke** [comment]
Actually, the workhorse is below. Theory nullified. Which f.shiftstat is the correct one?

**Comment by thenomain** [comment]
I had added some code that handled "sub-sheets", adding to the complexity of stats. While this system is not fully documented, I left the older code in the file by accident.

Fortunately, the second attribute was the newer one, so a straight copy-paste of the text applied the proper version of `&f.shiftstat`.
