### ISSUE TITLE
XP/Unaward Double-Tapping Totals

### ISSUE THREAD

**Issue by DazDyer** [thenomain/GMCCG#22]
When doing an /unaward in the xp system, it accurately deducts xp off of the top, but then also records the taken beats as spent, which gives an inaccurate xp readout. Beats taken through /unaward should not register as spent beats, since the total xp available seems to be a combination of awarded beats minus spent beats.

**Comment by thenomain** [comment]
Reinstalled the attribute `&c.xp/unaward` on the game in question. Works now. Good.
