### ISSUE TITLE
XP cost is not passing full stat name so always fails to find tags

### ISSUE THREAD

**Issue by ADHdev** [thenomain/GMCCG#24]
https://github.com/thenomain/GMCCG/blob/58357e59aedc848e079753756049960ccd4111c5/Z%20-%20Game%20Lines/Vampire%20the%20Requiem/VtR1%20-%20Core.txt#L1787

Change %3 to "discipline.%3" - otherwise all your Vamp in-clans will cost 4 XP.

Not sure why I haven't noticed this before.

**Comment by thenomain** [comment]
Whups. Fixed; thanks.
