### ISSUE TITLE
WtF: Prereqs off for Dedicated Locus

### ISSUE THREAD

**Issue by MelpomeneMU** [thenomain/GMCCG#25]
https://github.com/thenomain/GMCCG/blob/0384747909b3e598e8627bbe85e862e391487ddd/Z%20-%20Game%20Lines/Werewolf%20the%20Forsaken/WtF1%20-%20Core.txt#L490
```
&PREREQUISITE.MERIT.DEDICATED_LOCUS_() [v( d.dd )]=gte(udefault(%0/_merit.safe_place_(%1), 0), add(%2, 1))

&PREREQ-TEXT.MERIT.DEDICATED_LOCUS_() [v( d.dd )]=Safe place of this level or higher
```
Not sure that code is the best fix - there's probably a better function for it - but that was my fast fix.

**Comment by thenomain** [comment]
As of WtF2e, p106, Dedicated Locus just needs a Safe Place. Please re-bug if this has been errata'd  somewhere.

**Comment by MelpomeneMU** [comment]
Nudging to reopen, then. Original code says "Haven" and the merit is named "dedicated_locus_()". Plus, original code is checking for Haven merit, not Safe Place merit.

**Comment by thenomain** [comment]
Current code (https://github.com/thenomain/GMCCG/blob/master/Z%20-%20Game%20Lines/Werewolf%20the%20Forsaken/WtF1%20-%20Core.txt#L489): 
```
&merit.dedicated_locus_() [v( d.dd )]=1.2.3.4.5|*
&prerequisite.merit.dedicated_locus_() [v( d.dd )]=
	u( .has, %0, merit.safe_place_(%1) )
&prereq-text.merit.dedicated_locus_() [v( d.dd )]=Has Safe Place (<place name>)
&tags.merit.dedicated_locus_() [v( d.dt )]=werewolf.location
```

What am I missing?

**Comment by MelpomeneMU** [comment]
Ahh, you updated, I didn't see that. Cool! All good then. Thought the place had to match in dot levels though?

**Comment by thenomain** [comment]
This is why I left a book/page reference. WtF2e, p106, Dedicated Locus. It may have been errata'd and I have an old version.

I thought VtM2e's Haven was also "lesser than or equal to Safe Place" (and that's what my code says), but I just looked it up and nope, 1 dot of Safe Place. Again, tell me if this is old news.

**Comment by MelpomeneMU** [comment]
Just double-checked... blame Onyx Path. *facepalm* The prereq says "1 dot of safe place" but the last paragraph of the entry says "It must be anchored to a Safe Place of at least the same dot rating." POOR EDITING NO COOKIES FOR THEM. :P

**Comment by MelpomeneMU** [comment]
Vampire: So unclear as to be ridiculous. I'd keep Haven as-is, and blame Onyx Path.
