### ISSUE TITLE
.value_stat instead of .value

### ISSUE THREAD

**Issue by ADHdev** [thenomain/GMCCG#26]
https://github.com/thenomain/GMCCG/blob/f2422050a08170f38a83b87bfeb01e17b6fd0570/Z%20-%20Game%20Lines/Changeling%20the%20Lost/CtL3%20-%20Clarity%20System.txt#L167

Both references to .value_stat in lines 167-168 should probably be .value - .value_stat returns nothing on my codebase (might be my issue) while .value returns the actual numeric value.

**Comment by thenomain** [comment]
Yup, it was a typo on my part. Corrected; this is the only place in Clarity Systems it exists.

Reference: https://github.com/thenomain/GMCCG/blob/master/1%20-%20Data%20Dictionary/1a%20-%20Setup.txt#L213
