### ISSUE TITLE
Off by 1

### ISSUE THREAD

**Issue by MelpomeneMU** [thenomain/GMCCG#27]
https://github.com/thenomain/GMCCG/blob/710a86c503379f615277a9a63162246e0e5d3417/Z%20-%20Game%20Lines/Changeling%20the%20Lost/CtL3%20-%20Clarity%20System.txt#L943

Should be lt(... instead of lte(... because with Clarity 4 you get the warning for a condition on the first injury.

**Comment by thenomain** [comment]
I'm suspicious that it shouldn't be "lte" because it should include all the last three Clarity wound spots, but I'm also a trusting person who appreciates a good, complete issue report.

Re-open if this didn't work. Thanks.
