### ISSUE TITLE
Vitae max is off

### ISSUE THREAD

**Issue by MelpomeneMU** [thenomain/GMCCG#28]
https://github.com/thenomain/GMCCG/blob/710a86c503379f615277a9a63162246e0e5d3417/Z%20-%20Game%20Lines/Vampire%20the%20Requiem/VtR1%20-%20Core.txt#L135

Per the book on page 90, the numbers are off here. (Probably a version update?) Should be:

10 11 12 13 15 20 25 30 50 75

**Comment by thenomain** [comment]
Thanks for the heads-up.

Fixed.
