### ISSUE TITLE
XP.Gift not calculating correctly

### ISSUE THREAD

**Issue by LilithCoS** [thenomain/GMCCG#29]
Line 73 of GMCCG/4 - XP and Costs/4b - XP Costs.txt

the =unlock worked fine and charged 3xp.

xp/spend ward/gift of strength=purity

returns

<xp/spend> This stat has no Experience cost and must be set using 'stat/set'

And the attribute (I think it's the right one?) for the cost of gifts is:

XP.GIFT: [pemit(#350, gift: %#%r0: %0%r1: %1%r2: %2%r3: %3%r4: %4%r)][case( 1, strmatch(u( .value_full, %0, %3 ), Unlock), 0, cand(strmatch(u( .value_full, %0, %3 ), unlock.*), gt(get(%0/_free_gift_unlock), 0)), 0, cand( strmatch( %2, unlock ), hastag?( rest(%3, .), [u( .value_full, %0, bio.tribe )].[u( .value_full, %0, bio.auspice )], 0 ) ), 3, strmatch( %2, unlock ), 5, hastag?( rest(%3, .), wolf ), 1, 2)]

Also found that Tell (Phantom Pack) unlocks access for a wolf-blooded to the merit Pack Dynamics. I can't find the Werewolf/Wolf-Blooded merits in the gmccgen files :(

**Comment by thenomain** [comment]
This was determined to be added code that was a) broken and b) didn't look like it was being used anyway. Code reverted to original.
