### ISSUE TITLE
Command uses an = sign when documentation says /

### ISSUE THREAD

**Issue by MelpomeneMU** [thenomain/GMCCG#31]
https://github.com/thenomain/GMCCG/blob/6b7162f9a0674f305e17e67f2c212c2259d9c8f2/9%20-%20Critical%20Sub-Systems/9b%20-%20Aspirations.txt#L408

Line 408 and 409 have = signs but the job documentation (later in the process) says "asp/deny name**/**#".

On NOLA I changed it to / for both lines and asp/deny worked.

**Comment by thenomain** [comment]
Agreed. This is Not My Code™, but it's critical to the system. Consistency is a plus. Fixed.
