### ISSUE TITLE
Missing Condition

### ISSUE THREAD

**Issue by MelpomeneMU** [thenomain/GMCCG#32]
https://github.com/thenomain/GMCCG/blob/4a02228ca22e1011b4b877ba7b80fc2dbd00183a/Z%20-%20Game%20Lines/Changeling%20the%20Lost/CtL2%20-%20Conditions%20and%20Tilts.txt#L147

@fo me=&COND.COWED [v( d.ctdb )]=
	Cowed|0|
	
	Your character has been put in her place through the violence and dominance of another. She suffers a -2 penalty on any Physical and Social rolls to oppose the character who inflicted this Condition if she does not spend Willpower. Changelings with this Condition add one die to Clarity damage rolls.|

	Having another character demonstrate her superiority to you, some supernatural powers.|
	
	The character successfully injures or intimidates the character who inflicted the Condition, or the character regains Willpower through her Needle.|

	n/a|
	CtL.335

**Comment by thenomain** [comment]
Fixed. Thanks for the text. Added the return as per the book.
