### ISSUE TITLE
Obfuscate not obfuscare

### ISSUE THREAD

**Issue by MelpomeneMU** [thenomain/GMCCG#33]
https://github.com/thenomain/GMCCG/blob/0384747909b3e598e8627bbe85e862e391487ddd/Z%20-%20Game%20Lines/Vampire%20the%20Requiem/VtRz%20-%20The%20Descent%20-%20Bloodlines.txt#L823

No biggie but it came up on NOLA.

**Comment by thenomain** [comment]
Apparently fixed this a while ago. 

Don't Obfusc-hate, Obfus-care!
