### ISSUE TITLE
Fighting Finesse

### ISSUE THREAD

**Issue by Rucket82** [thenomain/GMCCG#36]
https://github.com/thenomain/GMCCG/blob/06c5d9e26d7a1ecec58da60c08962972858f3d88/1%20-%20Data%20Dictionary/1b%20-%20Core.txt#L548

When using .at_least, shouldn't it be Dexterity,3 instead of Dexterity:3?

**Comment by thenomain** [comment]
Yes, yes it should. Fixed. Thanks!
