### ISSUE TITLE
xp/award

### ISSUE THREAD

**Issue by Rucket82** [thenomain/GMCCG#37]
https://github.com/thenomain/GMCCG/blob/4909df1643c564a20b055edcda15593c06a70cdb/4%20-%20XP%20and%20Costs/4c%20-%20XP%20and%20Advancement.txt#L1054-L1056

https://github.com/thenomain/GMCCG/blob/4909df1643c564a20b055edcda15593c06a70cdb/4%20-%20XP%20and%20Costs/4c%20-%20XP%20and%20Advancement.txt#L1065-L1067

Unless I am mistaken, these two snippets of code appear to be doing the same exact thing but are both part of the same code block.

**Comment by thenomain** [comment]
Deleted the second instance. Mostly harmless so categorizing it as a typo, even tho it'd have a minor effect on runtime efficiency. Probably happened when I moved the code block, used "copy" instead of "cut".

Thanks!
