### ISSUE TITLE
Minor Typo in xp/unspend

### ISSUE THREAD

**Issue by Rucket82** [thenomain/GMCCG#39]
https://github.com/thenomain/GMCCG/blob/4909df1643c564a20b055edcda15593c06a70cdb/4%20-%20XP%20and%20Costs/4c3%20-%20XP%20Unspend.txt#L203

Should be:  occurred

**Comment by thenomain** [comment]
Well this is me learning things with git, but you get the idea. Typo fixed, thanks.
