### ISSUE TITLE
Error in census failure message

### ISSUE THREAD

**Issue by skewskewskew** [thenomain/GMCCG#4]
GMCCG/A - Bonus Sub-Systems/A1 - Census.txt Line 56

https://github.com/thenomain/GMCCG/blob/master/A%20-%20Bonus%20Sub-Systems/A1%20-%20Census.txt#L56

The command calls `u( .msg.` when it should be `u( .msg,` with a comma, not a period.

**Comment by thenomain** [comment]
Fixed in commit bde40c0b2a2583252f13f0c4e0a0adb063a31e4f

Thanks.
