### ISSUE TITLE
XP/Deduct typo

### ISSUE THREAD

**Issue by Rucket82** [thenomain/GMCCG#41]
https://github.com/thenomain/GMCCG/blob/d8855c05aeee068642a6685202f0e863de519319/4%20-%20XP%20and%20Costs/4c5%20-%20XP%20Deduct.txt#L153-L158

I believe there should be a , added after u( f.transaction.end ) on line 155.

**Comment by thenomain** [comment]
Technically this would work fine, as 'u( f.transaction.end ) type of etc...' would evaluate properly, but it's ugly and needed fixed.

Thanks!
