### ISSUE TITLE
Wrong pool

### ISSUE THREAD

**Issue by Rucket82** [thenomain/GMCCG#46]
https://github.com/thenomain/GMCCG/blob/6e128d9434f778825ec19feb4a213cf12f354fbe/Z%20-%20Game%20Lines/Changeling%20the%20Lost/CtL1%20-%20Core.txt#L2676

glamour s/b goblin_debt

**Comment by thenomain** [comment]
Don't know what "s/b" means, but the error was self-evident. Thanks.
