### ISSUE TITLE
Line missing comma.

### ISSUE THREAD

**Issue by Rucket82** [thenomain/GMCCG#49]
https://github.com/thenomain/GMCCG/blob/10ba23ce6a4a7c6d96caf2eca6f344b94af3d744/9%20-%20Critical%20Sub-Systems/9c%20-%20Spend%20and%20Regain.txt#L206

There should be a comma at the end of this line.

**Comment by thenomain** [comment]
No idea how I missed this as it's been in production on various games for a while. Thanks.
