### ISSUE TITLE
Beast chargen missing sheet blocks

### ISSUE THREAD

**Issue by ADHdev** [thenomain/GMCCG#5]
I ended up with the code below but I'd be delighted to put up something better. I'm using the default Sheet: Rows for now.

`
&bio.default.beast [v(d.nsc)]=full_name birthdate concept template legend life family hunger

&traits.morality.beast [v(d.nsc)]=ulocal(f.cheat_getstat.morality, %0, satiety)

&block.traits.beast [v(d.sheet)]=strcat(setq(w, 38), setq(t, 10), setq(z, u(display.trait-and-value, u(traits.supernatural_resistance, %0), inc(strlen(Lair)), %qw, numeric)), vcolumns(%qw:%qz, |, %b), %r,)

&powers.nightmares [v(d.nsc)]=iter(sort(edit(lattr(%0/_nightmare.*), _nightmare.,)), ulocal(f.cheat_getstat.with_name, %0, nightmare.%i0, numeric),, |)

&powers.atavisms [v(d.nsc)]=iter(sort(edit(lattr(%0/_atavism.*), _atavism.,)), ulocal(f.cheat_getstat.with_name, %0, atavism.%i0, numeric),, |)

&block.powers.beast [v(d.sheet)]=strcat(setq(w, 79), setq(t, 70), setq(d, u(powers.nightmares, %0)), setq(v, u(powers.atavisms, %0)), setq(b, iter(%qd, ulocal(display.trait-and-value, %i0, %qt, %qw, numeric, .), |, |)), divider(Nightmares), %r, iter(%qb, %i0, |, %r), %r, strcat(divider(Atavisms), %r, table(%qv, %qt, %qw, |), %r,), null(to be continued),)
`

**Comment by ADHdev** [comment]
Found a bug with the code above: edit() is case sensitive.

`
&powers.nightmares [v(d.nsc)]=iter(sort(edit(lattr(%0/_nightmare.*), _NIGHTMARE.,)), ulocal(f.cheat_getstat.with_name, %0, nightmare.%i0, numeric),, |)

&powers.atavisms [v(d.nsc)]=iter(sort(edit(lattr(%0/_atavism.*), _ATAVISM.,)), ulocal(f.cheat_getstat.with_name, %0, atavism.%i0, numeric),, |)
`

**Comment by thenomain** [comment]
I'm finally folding the code into the core files. Have you completed this? :: `null( to be continued ),`

**Comment by ADHdev** [comment]
Just checked and nope, the null is still in there. Beast sheets look OK too. Not sure why that was there - I copied it from something else I think? Sorry, it's been too long, I'm not sure.

**Comment by thenomain** [comment]
Closing issue because I'm unlikely to get back to Beast any time soon.
