### ISSUE TITLE
Possible Missing tags line?

### ISSUE THREAD

**Issue by Rucket82** [thenomain/GMCCG#50]
https://github.com/thenomain/GMCCG/blob/10ba23ce6a4a7c6d96caf2eca6f344b94af3d744/Z%20-%20Game%20Lines/Changeling%20the%20Lost/CtL1%20-%20Core.txt#L81-L83

Should there be a line like the following here?

`&prefix.changeling_-_contracts [v(d.dt)]=tags.contract.`

**Comment by thenomain** [comment]
It couldn't hurt and for completeness' sake, yes!
