### ISSUE TITLE
v(d.dd) should be v(d.dt)

### ISSUE THREAD

**Issue by Rucket82** [thenomain/GMCCG#51]
https://github.com/thenomain/GMCCG/blob/10ba23ce6a4a7c6d96caf2eca6f344b94af3d744/Z%20-%20Game%20Lines/Mage%20the%20Awakening/MtA1%20-%20Core.txt#L225

[v(d.dd)] should be [v(d.dt)] here as tags go to the tags object.

**Comment by thenomain** [comment]
You may also note that the text for legacy is `x.x.x.x.x.x.x.x` showing off my incompleteness and/or desire to make the game-runner to fill this in. Realistically it should include the legacies from the core book.

As usual, thanks.
