### ISSUE TITLE
Attributes Swapped

### ISSUE THREAD

**Issue by Rucket82** [thenomain/GMCCG#52]
https://github.com/thenomain/GMCCG/blob/10ba23ce6a4a7c6d96caf2eca6f344b94af3d744/Z%20-%20Game%20Lines/Mage%20the%20Awakening/MtA1%20-%20Core.txt#L363-L364

The text in &prerequisite should be in &prereq-text and vice versa.

**Comment by thenomain** [comment]
Derp. Fixed.
