### ISSUE TITLE
Xp/spend trying to charge 4xp for in-clan disc

### ISSUE THREAD

**Issue by CoSLilith** [thenomain/GMCCG#54]
+----+ Bio +-------------------------------------------------------------------+
Embrace Date: June 23, 1972             Template    : Vampire                  
Concept     : Warrior Scholar           Mask        : Courtesan                
Clan        : Gangrel                   Dirge       : Scholar                  
Bloodline   : Ahrimanes                 Coterie     : <not set>                
Covenant    : Ordo Dracul               Praxes      : Undercity                
Mystery Coil: Coil of the Wyrm                                                 
                                                                               
<xp/cost> The cost for Aaron to raise Protean from 2 to 3 is 4 Experience. (Not enough Experience.)

The only difference I see in the code is the bloodlines stuff? So maybe that's a starting point?

**Comment by thenomain** [comment]
Processed statpath on `&xp.discipline` incorrectly.

**Comment by thenomain** [comment]
Changeling contracts not discounting correctly for Favored Regalia status (chosen or Seeming) due to case sensitivity in setinter().
