### ISSUE TITLE
Fae-Touched Glamour Issue

### ISSUE THREAD

**Issue by CoSLilith** [thenomain/GMCCG#56]
Glamour doesn't want to spend for Fae-Touched.

spend glamour=1 for Boon of the Scuttling Spider
spend glamour=1

<glamour/spend> You can't spend that much at one time
<glamour/spend> You can't spend that much at one time

**Comment by thenomain** [comment]
Fixed by extending the Wyrd -> Glamour Spend chart from Wyrd 1-10 to Wyrd 1-11 and comparing to Wyrd+1.
