### ISSUE TITLE
Display Needle & Thread on same side of Changeling Sheet

### ISSUE THREAD

**Issue by cmdr-taskene** [thenomain/GMCCG#57]
It's a quick and dirty fix, could probably be rejiggered to be less crap:

&BIO.DEFAULT.CHANGELING <sheet system obj>=full_name birthdate concept %R %R needle thread template court seeming kith [if( hasattr( %0, _bio.motley ), motley )]

Inserting linebreaks instead of a .bio field works to force fields lower, put in enough and it shunts them to the right.

**Comment by cmdr-taskene** [comment]
Alternately, removing the if statement from around the motley display seems to make the columns all line up nice and neatly:

+----------------------------+ Maintenance (#615) +----------------------------+
+----+ Bio +-------------------------------------------------------------------+
Full Name   : <not set>                 Template    : Changeling               
Birthdate   : <not set>                 Court       : Courtless                
Concept     : <not set>                 Seeming     : <not set>                
Needle      : <not set>                 Kith        : <not set>                
Thread      : <not set>                 Motley      : <not set>                
+------------------------------------------------------------------------------+

**Comment by thenomain** [comment]
Sheet prettied. Thanks.
