### ISSUE TITLE
Werewolf Favored Form

### ISSUE THREAD

**Issue by CoSLilith** [thenomain/GMCCG#59]
+----------------------+ Favored Form (<type>) [Merit] +-----------------------+
  Values: 1, 2, 3, 4, and 5
  Type: Dalu, Gauru, Urshul, or Urhan
  Details: Any

  Templates: Werewolf
  Prerequisites: Stamina 3, Survival 2
+------------------------------------------------------------------------------+
Pre-req text is wrong, seems to match fortified form. Fixed in-game, may need updated in the code :3

**Comment by thenomain** [comment]
This was fixed just not applied. Thanks for the heads-up!
