### ISSUE TITLE
Beast chargen missing chargen checks

### ISSUE THREAD

**Issue by ADHdev** [thenomain/GMCCG#6]
Here's what I ended up with:

`
&CHECK.BIO.BEAST cg=legend life family hunger

&F.ALLOCATED.POWER-TRAIT.BEAST cg=mul(dec(first(get(%0/_advantage.lair), .)), 5)

&F.ALLOCATED.NIGHTMARES cg=ladd(iter(lattr(%0/_nightmare.*), get(%0/%i0)))

&f.allocated.atavisms cg =localize(strcat(setq(d, edit(lattr(%0/_ATAVISM.*), _ATAVISM., ATAVISM.)), setq(i, u(f.list-stats-tags, %0, atavism, get(%0/_bio.family))), ladd(iter(setdiff(%qd, %qi), get(%0/_%i0))), `, ladd(iter(%qi, get(%0/_%i0))),))

&check.atavisms [v(d.cg)]=udefault(check.atavisms.[get(%0/_bio.template)], ** check failed **, %0)

&check.atavisms.beast [v(d.cg)]=strcat(setq(9, u(f.allocated.atavisms, %0)), setq(t, ladd(%q9, `)), setq(i, elements(%q9, 1, `)), %b, %b, ansi(h, Total atavisms), :, %b, if(eq(%qt, 0), ansi(xh, <none>), %qt), %b, %(of 2%), %b, u(check.atavisms.beast.total, %qt), %r, %b, %b, %b, %b, ansi(h, In-family), :, %b, if(eq(%qi, 0), ansi(xh, <none>), %qi), %b, %(at least 1%), %b, u(check.atavisms.beast.in-family, %qi), %r)

&check.atavisms.beast.total [v(d.cg)]=u(display.check.ok-no, eq(%0, 2))

&check.atavisms.beast.in-family [v(d.cg)]=u(display.check.ok-no, gte(%0, 1))

&check.nightmares [v(d.cg)]=udefault(check.nightmares.[get(%0/_bio.template)], ** check failed **, %0)

&check.nightmares.beast [v(d.cg)]=strcat(setq(9, u(f.allocated.nightmares, %0)), setq(t, ladd(%q9, `)), setq(i, elements(%q9, 2, `)), setq(o, elements(%q9, 1, `)), %b, %b, ansi(h, Total nightmares), :, %b, if(eq(%qt, 0), ansi(xh, <none>), %qt), %b, %(of 2%), %b, u(check.nightmares.beast.total, %qt), %r)

&check.nightmares.beast.total [v(d.cg)]=u(display.check.ok-no, eq(%0, 2))

&check.chargen.beast [v(d.cg)]=strcat(u(check.atavisms, %0, beast), u(check.nightmares, %0, beast))

`

**Comment by thenomain** [comment]
Added in commit d835a8d42bf4e062c8515802ca9d9352f61202e7

Thanks!
