### ISSUE TITLE
Iron Skin Merit Prereq

### ISSUE THREAD

**Issue by cmdr-taskene** [thenomain/GMCCG#62]
PREREQUISITE.MERIT.IRON_SKIN: cand( cor( u( .list_at_least, %0, merit.martial_arts, 2 ), u( .list_at_least, %0, merit.muay_thai, 2 )), u( .at_least, %0, merit.street_fighting, 2 ))

Changed to

PREREQUISITE.MERIT.IRON_SKIN: cand( u( .at_least, %0, attribute.stamina, 3), cor( u( .at_least, %0, merit.martial_arts, 2 ), u( .at_least, %0, merit.muay_thai, 2 ), u( .at_least, %0, merit.street_fighting, 2 )))

Adding Stamina 3+ check and putting Street Fighting Merit check into the cand()

**Comment by thenomain** [comment]
fixed, thanks!
