### ISSUE TITLE
Werewolf chargen checks use "unlock" instead of "Unlock" in case-sensitive functions

### ISSUE THREAD

**Issue by ADHdev** [thenomain/GMCCG#7]
setdiff(Unlock, unlock) returned a value since it's case-sensitive - that resulted in facets not being checked correctly in the check.gifts.* functions.

Edited code:
`
&check.gifts.moon [v(d.cg)]=strcat(setq(a, u(v(d.dd)/.value_full, %0, bio.auspice)), setq(r, filter(v(d.sfp)/fil.list-stats-tags, lattr(v(d.dd)/renown.*),,, %qa)), setq(v, u(v(d.dd)/.value, %0, %qr)), setq(x, elements(%1, 1, `)), setq(k, eq(words(%qx), 1)), %b%b, ansi(h, Moon Gift), :, %b, titlestr(edit(itemize(%qx), _, %b)), %b, u(display.check.ok-no, %qk), if(%qk, strcat(setq(f, setdiff(u(v(d.dd)/.value_full, %0, gift.%qx), Unlock, .)), %r, %b %b%b, %(, ansi(h, Facets), :, %b, setr(x, words(%qf, .)), %b, out of %qv, %), %b, u(display.check.ok-no, eq(%qx, %qv)),)), %r)

&check.gifts.auspice [v(d.cg)]=strcat(setq(a, u(v(d.dd)/.value_full, %0, bio.auspice)), setq(x, elements(%1, 2, `)), setq(k, eq(words(%qx), 1)), %b%b, ansi(h, Shadow Gift%, Auspice), :, %b, titlestr(edit(itemize(%qx), _, %b)), %b, %(of one%), %b, u(display.check.ok-no, %qk), if(%qk, strcat(setq(f, setdiff(u(v(d.dd)/.value_full, %0, gift.%qx), Unlock, .)), %r, %b %b%b, %(, ansi(h, Facets), :, %b, setr(x, words(%qf, .)), %b, out of 1, %), %b, u(display.check.ok-no, eq(%qx, 1)))), %r)
`

**Comment by thenomain** [comment]
Fixed. Code to be pushed when I have access.
