### ISSUE TITLE
Beast XP costs not set

### ISSUE THREAD

**Issue by ADHdev** [thenomain/GMCCG#8]
Not sure this is right but:
`
&d.restricted.types.beast [v(d.xpas)]=atavism.nightmare

&d.restricted.stats.beast [v(d.xpas)]=lair

&xp.nightmare [v(d.xpcd)]=u(cost.standard, 3, %1, %2)

&xp.atavism [v(d.xpcd)]=case(1, hastag?(%3, u(.value_full, %0, bio.family)), u(cost.standard, 3, %1, %2), u(cost.standard, 4, %1, %2))

&xp.advantage.lair [v(d.xpcd)]=u(cost.standard, 5, %1, %2)

`

**Comment by thenomain** [comment]
This looks right, tho I would make the "atavism" formula: 

`u( cost.standard, if( hastag?( %3, u(.value_full, %0, bio.family)), 3, 4 ), %1, %2 )`

As a warning, the Beast files are absolutely not complete. I got stuck somewhere along the way, though I can't remember where at the moment. I think in their power set.

Let me know if this XP set works so I can fold it in and close this out.

**Comment by ADHdev** [comment]
I like that fix better than mine, much cleaner. Final line:
``
&xp.atavism [v(d.xpcd)]=u( cost.standard, if( hastag?( %3, u(.value_full, %0, bio.family)), 3, 4 ), %1, %2 )
``
Far as I can tell it works. I'll let you know if we get reports of incorrect costs.

**Comment by thenomain** [comment]
Added in commit d835a8d42bf4e062c8515802ca9d9352f61202e7

Thanks!
