### ISSUE TITLE
Werewolf cgen counts shadow gifts separately

### ISSUE THREAD

**Issue by ADHdev** [thenomain/GMCCG#9]
Apparently you're supposed to be able to take two shadow gifts from _either_ your auspice or tribe lists, or one from both. The current Werewolf setup requires one from both. I coded a quick fix:

``
&CHECK.GIFTS cg=strcat(setq(g, u(f.allocated.gifts, %0)), wdivider(Chargen Levels: Gifts), %r, u(check.gifts.moon, %0, %qg), u(check.gifts.shadow, %0, %qg), u(check.gifts.wolf, %0, %qg), u(check.gifts.other, %0, %qg),)

&CHECK.GIFTS.SHADOW cg=strcat(setq(x, extract(%1, 2, 2, `,)), setq(k, gte(words(%qx), 1)), %b%b, ansi(h, Shadow Gift%, Auspice or Tribe), :, %b, titlestr(edit(itemize(%qx), _, %b)), %b, %(of two%), %b, u(display.check.ok-no, %qk), if(%qk, strcat(setq(f, iter(%qx, setdiff(u(v(d.dd)/.value_full, %0, gift.%i0), Unlock, .),, .)), %r, %b %b%b, %(, ansi(h, Facets), :, %b, setr(x, words(%qf, .)), %b, out of 2, %), %b, u(display.check.ok-no, eq(%qx, 2)))), %r)
``

**Comment by thenomain** [comment]
Can you get me a page number for the WtAv2 book? I'm usually really good about this. Thanks.

**Comment by ADHdev** [comment]
From the staffer: Page 83, Gifts and Rites, "She also receives two Facets of two Shadow Gifts from her tribe or auspice." If it meant one of each it would say, "She receives two Facets of Shadow Gifts, one each from auspice or tribe."

**Comment by thenomain** [comment]
Yup, that's a pretty fair assessment. I left in the old code in case anyone disagrees. Thanks!

commit cf7ded4e269e2d14dfbf81378b7f6e332afe9324

**Comment by CoSLilith** [comment]
Tried to apply the fix, and now it displays as:

+----+ Chargen Levels: Gifts +-------------------------------------------------+
  Moon Gift: New_moon's_gift [OK]
    (Facets: 2 out of ) [no]
  Shadow Gift, Auspice or Tribe: Gift of Stealth and Gift of Technology (of two) [OK]
    (Facets: 2 out of 2) [OK]
  Wolf Gifts:  [OK]
    (Facets: 0) [OK]

**Comment by thenomain** [comment]
This was recently fixed in some other bug or other. Woo!
